[workspace]
resolver = "3"
members = [
  "crates/*"
]

[profile.release]
opt-level = "s" # Optimize for binary size, as DBus messages are the more likely bottleneck
lto = true # Link time optimization
