[package]
name = "flurr-dbus"
version = "0.1.0"
license = "MPL-2.0"
description = "DBus bindings for Flurr"
keywords = ["api"]
categories = ["api-bindings"]
repository = "https://github.com/mimvoid/flurr"
edition = "2024"

[dependencies]
bitflags = "2.9.4"
dbus = "0.9.9"
